nguage: node_js
node_js:
	- "6.12.0"

branches:
	only:
		- master

	before_script:
		- npm install -g firebase-tools
		- npm install -g wintersmith

	script:
		- wintersmith build

	after_success:
		- firebase deploy --token=${ftkn}
